name: key_wallet
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  crypto: ^3.0.1
  mysql1: ^0.19.2
  moor: ^4.6.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  moor_flutter: ^4.0.0
  drift: ^1.0.1
  hive: ^2.0.4

  hive_flutter: ^1.1.0
  rxdart: ^0.27.2
  cryptography: ^2.0.2
  encrypt: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  drift_dev: ^1.0.2
  build_runner: ^2.1.4
  hive_generator: ^1.1.1


flutter:


  uses-material-design: true


  assets:
    - assets/images/logo.png


